# Generated by Django 5.1.15 on 2026-07-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Aktivitas",
                "verbose_name_plural": "Daftar Aktivitas",
            },
        ),
    ]
