# Generated by Django 5.1.15 on 2026-07-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_activity_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text="Contoh: v1.1.0", max_length=50),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("core", "Core Update"),
                            ("page", "Page Update"),
                            ("bugfix", "Bugfix"),
                            ("feature", "New Feature"),
                        ],
                        default="feature",
                        max_length=20,
                    ),
                ),
                ("release_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "System Update",
                "verbose_name_plural": "System Updates",
                "ordering": ["-release_date"],
            },
        ),
    ]
