# Generated by Django 5.1.15 on 2026-07-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Data tambahan dari registration wizard (konfigurasi via REGISTRATION_STEPS)",
                verbose_name="extra data",
            ),
        ),
    ]
