# Generated by Django 5.1.15 on 2026-08-02 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicaluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Passkey Device', help_text='Nama perangkat untuk identifikasi user', max_length=255, verbose_name='device name')),
                ('credential_id', models.CharField(max_length=255, unique=True, verbose_name='credential ID')),
                ('public_key', models.TextField(verbose_name='public key')),
                ('sign_count', models.PositiveIntegerField(default=0, verbose_name='sign count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'passkey credential',
                'verbose_name_plural': 'passkey credentials',
                'ordering': ['-created_at'],
            },
        ),
    ]
