# Generated by Django 5.1.15 on 2026-08-19 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passkeycredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='Base32 encoded secret key untuk TOTP generation', max_length=64, verbose_name='secret key')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Apakah perangkat sudah berhasil diverifikasi dengan token pertama', verbose_name='is confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp penggunaan token terakhir untuk mencegah replay attack', null=True, verbose_name='last used at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'TOTP device',
                'verbose_name_plural': 'TOTP devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TOTPBackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='Hashed backup code untuk verifikasi sekali pakai', max_length=255, verbose_name='code hash')),
                ('is_used', models.BooleanField(default=False, help_text='Status apakah kode pemulihan ini sudah digunakan', verbose_name='is used')),
                ('used_at', models.DateTimeField(blank=True, help_text='Waktu saat kode cadangan digunakan', null=True, verbose_name='used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='accounts.totpdevice', verbose_name='TOTP device')),
            ],
            options={
                'verbose_name': 'TOTP backup code',
                'verbose_name_plural': 'TOTP backup codes',
                'ordering': ['is_used', '-created_at'],
            },
        ),
    ]
