# Generated by Django 5.1.15 on 2026-08-09 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionTraceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('feature_name', models.CharField(db_index=True, max_length=100)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('class_function_path', models.CharField(max_length=255)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('db_query_count', models.IntegerField(default=0)),
                ('service_units_consumed', models.FloatField(default=0.0)),
                ('status_code', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execution Trace Log',
                'verbose_name_plural': 'Execution Trace Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
