# Generated by Django 5.1.15 on 2026-07-23 14:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Kategori",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="Pemasok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Pemasok",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="Produk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                (
                    "sku",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "harga",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("stok", models.IntegerField(default=0)),
                ("deskripsi", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("stok_menipis", "Stok Menipis"),
                            ("habis", "Habis"),
                            ("draf", "Draf"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produk",
                        to="inventory.kategori",
                    ),
                ),
                (
                    "pemasok",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produk",
                        to="inventory.pemasok",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Produk",
                "ordering": ["-updated_at"],
            },
        ),
    ]
